
INSERT INTO ddd_locations (ddd, state_code, state_name, capital, region) VALUES
(12, 'SP', 'São Paulo', 'São Paulo', 'Sudeste'),
(13, 'SP', 'São Paulo', 'São Paulo', 'Sudeste'),
(14, 'SP', 'São Paulo', 'São Paulo', 'Sudeste'),
(15, 'SP', 'São Paulo', 'São Paulo', 'Sudeste'),
(16, 'SP', 'São Paulo', 'São Paulo', 'Sudeste'),
(17, 'SP', 'São Paulo', 'São Paulo', 'Sudeste'),
(18, 'SP', 'São Paulo', 'São Paulo', 'Sudeste'),
(19, 'SP', 'São Paulo', 'São Paulo', 'Sudeste'),
(22, 'RJ', 'Rio de Janeiro', 'Rio de Janeiro', 'Sudeste'),
(24, 'RJ', 'Rio de Janeiro', 'Rio de Janeiro', 'Sudeste'),
(42, 'PR', 'Paraná', 'Curitiba', 'Sul'),
(43, 'PR', 'Paraná', 'Curitiba', 'Sul'),
(44, 'PR', 'Paraná', 'Curitiba', 'Sul'),
(45, 'PR', 'Paraná', 'Curitiba', 'Sul'),
(46, 'PR', 'Paraná', 'Curitiba', 'Sul'),
(47, 'SC', 'Santa Catarina', 'Florianópolis', 'Sul'),
(49, 'SC', 'Santa Catarina', 'Florianópolis', 'Sul'),
(53, 'RS', 'Rio Grande do Sul', 'Porto Alegre', 'Sul'),
(54, 'RS', 'Rio Grande do Sul', 'Porto Alegre', 'Sul'),
(55, 'RS', 'Rio Grande do Sul', 'Porto Alegre', 'Sul'),
(73, 'BA', 'Bahia', 'Salvador', 'Nordeste'),
(74, 'BA', 'Bahia', 'Salvador', 'Nordeste'),
(75, 'BA', 'Bahia', 'Salvador', 'Nordeste'),
(77, 'BA', 'Bahia', 'Salvador', 'Nordeste'),
(87, 'PE', 'Pernambuco', 'Recife', 'Nordeste'),
(88, 'CE', 'Ceará', 'Fortaleza', 'Nordeste'),
(89, 'PI', 'Piauí', 'Teresina', 'Nordeste'),
(93, 'PA', 'Pará', 'Belém', 'Norte'),
(94, 'PA', 'Pará', 'Belém', 'Norte'),
(97, 'AM', 'Amazonas', 'Manaus', 'Norte'),
(99, 'MA', 'Maranhão', 'São Luís', 'Nordeste')
ON CONFLICT (ddd) DO NOTHING;
